name: ecobrick_app
version: 1.2.0+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  lottie: 1.3.0
  flutter_svg: ^1.1.1
  chewie: ^1.3.4
  video_player: ^2.4.5
  get_storage: ^2.0.3
  mrx_charts: ^0.1.3
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.40
  
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli-SemiBold.ttf
